project:
  type: website
  output-dir: docs

website:
  title: "Statistics II - Data Visualization"
  navbar:
    left:
      - href: slides.qmd
        text: Week 3
      - href: slides_tr.qmd
        text: Hafta 3

format:
  html:
    theme: cosmo
    toc: true
