project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Statistics II - Data Visualization"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Week 3
      - href: slides_tr.qmd
        text: Hafta 3

format:
  html:
    theme: cosmo
    toc: true
