project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides_week7.qmd"
    - "!slides_week7_tr.qmd"
    - "!week7_t/instructor_notes.qmd"

website:
  title: "Statistics II - Data Visualization"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Week 3
      - href: slides_tr.qmd
        text: Hafta 3
      - href: slides_week4.qmd
        text: Week 4
      - href: slides_week8.qmd
        text: Anova

format:
  html:
    theme: cosmo
    toc: true
